export const global_data = {
  en: {
    title: "Perident Dental Clinic Győr",
    contact: {
      enquire: "Enquire",
      name: "Name",
      email: "Email",
      message: "Message",
      phone: "Telephone",
      message_hint: "I'd like to ask a question about...",
      send: "Send",
    },
    opening_hours: {
      title: "Opening hours",
      monday: "Monday",
      tuesday: "Tuesday",
      wednesday: "Wednesday",
      thursday: "Thursday",
      friday: "Friday",
      saturday: "Saturday",
      sunday: "Sunday",
      closed: "Closed",
    },
  },
  hu: {
    title: "PERIDENT Fogászat Győr",
    contact: {
      enquire: "Érdeklődni",
      name: "Név",
      email: "E-mail",
      message: "Üzenet",
      phone: "Telefon",
      message_hint: "Van egy kérdésem...",
      send: "Küld",
    },
    opening_hours: {
      title: "Nyitvatartási idő",
      monday: "Hétfő",
      tuesday: "Kedd",
      wednesday: "Szerda",
      thursday: "Csütörtök",
      friday: "Péntek",
      saturday: "Szombat",
      sunday: "Vasárnap",
      closed: "Zárva",
    },
  },
  de: {
    title: "Perident Zahnklinik Győr",
    contact: {
      enquire: "Anfragen",
      name: "Name",
      email: "E-mail",
      message: "Botschaft",
      phone: "Telefon",
      message_hint: "Ich habe eine Frage...",
      send: "Senden",
    },
    opening_hours: {
      title: "Öffnungszeiten",
      monday: "Montag",
      tuesday: "Dienstag",
      wednesday: "Mittwoch",
      thursday: "Donnerstag",
      friday: "Freitag",
      saturday: "Samstag",
      sunday: "Sonntag",
      closed: "Abgeschlossen",
    },
  },
}